# Generated by Django 3.1.3 on 2023-05-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='total_learners',
            field=models.IntegerField(null=True),
        ),
    ]
